### ISSUE TITLE
FCM

### ISSUE THREAD

**Issue by punitm0** [SurfEdge/flarum-mobile-android#21]
Update README.md on how to send Notifications using FCM.

**Comment by Felli** [comment]
Setup can be found on [Set Up a Firebase Cloud Messaging Client App on Android](https://firebase.google.com/docs/cloud-messaging/android/client), as for FCM that is implemented into this app, it does Push Notifications automatically, or at least it should. As for the reasons behind my revert request seen in #20 this is because it would require recoding `MyFirebaseMessagingService.java` to fix some of the issues, so in short as long as you follow the [How to setup](https://github.com/SurfEdge/flarum-mobile-android#how-to-setup) Push Notifications should auto enable unless I've missed something (Which I won't deny is possible).
